apiVersion: zalando.org/v1
kind: StackSet
metadata:
  labels:
    application: ss-stack
  name: ss-stack
spec:
  externalIngress:
    backendPort: 5678
  stackTemplate:
    spec:
      replicas: 1
      version: v2
      podTemplate:
        spec:
          containers:
            - name: gw-test-app
              image: hashicorp/http-echo
              args: ["-text", "Stack V2"]
              ports:
                - containerPort: 5678
              resources:
                requests:
                  cpu: 1
                  memory: 100Mi
                limits:
                  memory: 100Mi