apiVersion: zalando.org/v1
kind: FabricGateway
metadata:
  name: managed-by-stackset-1
spec:
  x-external-service-provider:
    stackSetName: ss-stack
    hosts:
      - test.smart-product-platform-test.zalan.do
  paths:
    /api:
      get: {}