apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: "{{{ COMPOSITE_CONTROLLER_NAME }}}"
webhooks:
  - name: "{{{ COMPOSITE_CONTROLLER_NAME }}}.check.webhook"
    failurePolicy: Fail
    sideEffects: None
    rules:
      - apiGroups:
          - zalando.org
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
        resources:
          - "{{{ CRD_PLURAL }}}"
    clientConfig:
      service:
        namespace: fabric
        name: "{{{ COMPOSITE_CONTROLLER_NAME }}}"
        path: "/validate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVrVENDQW5tZ0F3SUJBZ0lFZHJXOEpEQU5CZ2txaGtpRzl3MEJBUXdGQURCYU1Rc3dDUVlEVlFRR0V3SkoNClJURVBNQTBHQTFVRUNCTUdSSFZpYkdsdU1ROHdEUVlEVlFRSEV3WkVkV0pzYVc0eEVEQU9CZ05WQkFvVEIxcGgNCmJHRnVaRzh4RnpBVkJnTlZCQXNURGtsdVpuSmhjM1J5ZFdOMGRYSmxNQjRYRFRJeE1ESXhOekUyTkRJME5sb1gNCkRUUTRNRGN3TkRFMk5ESTBObG93VWpFTE1Ba0dBMVVFQmhNQ1NVVXhEekFOQmdOVkJBZ1RCa1IxWW14cGJqRVANCk1BMEdBMVVFQnhNR1JIVmliR2x1TVJBd0RnWURWUVFLRXdkYVlXeGhibVJ2TVE4d0RRWURWUVFMRXdaR1lXSnkNCmFXTXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFERXY5SkliUFhJcHlMQ1V1RTENClRsSDhzbVM4ZWdNcElYQWd4VmVvVzRUQVRUWE1PdFZlMGwramNzZmZpRDFBU1lxb3o0UXh3TTUwdVJVNU1Zd1YNClQ1NVMrNjMwN2dGVXhFMlZkY2J1dzZjUjhPR0RIY1pkeUgzR2ZBWFgwdlNkc25NL0ZEV2tKR1VuL05oMTFlSUsNClVNVWxOZUJyeFl0UnBCdWpzYzdCejFiNGNld0I0QjdvU1VqWnA0Q3kva3Nxam9sOWlHU2duNnRUKytiQkRlUkYNClNQdHRYbUdvSFM2UWFQbkVQLzdON3pYNDBmSjV1V1dVT0xCdEo2STkwOE9PTHVnbDgzczBaNFNVTExvcmFpdEkNCmdwbGFhK3FXa2k2OWtuQXJrSjFkbEdzby83NEFkdGQveEtZaWo0alhwM2MrOTFhVnNJN1UwNWtDZDVHbGVML0kNCndHY2pBZ01CQUFHalp6QmxNQjBHQTFVZERnUVdCQlFhVVk0KzJoa1ArL2ROZmlmM2lhWDREMkQ2d2pBT0JnTlYNCkhROEJBZjhFQkFNQ0JhQXdId1lEVlIwakJCZ3dGb0FVTXZrdm8vek9jVUxjbmhKR0FmVmo5ZVBhVjFFd0V3WUQNClZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0RRWUpLb1pJaHZjTkFRRU1CUUFEZ2dJQkFGM2k4VE5CVEQ3UDFjZmkNCllVckR2aTVSajhaMHFMSW15M3V1c1lNRlRtODNmeTVJNHZMTGNBcE00alhvRDNGRHBvSEhaUzA3b2I3aDdYM2oNCjdTYndEUmgvTzhNT3RQS1JqaUZnWWJLcTJJTmljVHliRGJpM0g5Z1pUYXg4eURmNjM4THM0TjdCMDhUa00yRWYNCjJHdTNJM0I3MEhGejgvQ2tudEtCR2RCZU1yNmExRU05aU5ncHlWREo3TWYvb2VmMml5dXBZa3Z0RitqZGQyYSsNCkxpeExyaFZuYVFpbU0zT2ZaLzJjbmhLZGREcWNoeFJDQnM1cjhseHlKVGxrL3FIaHQzUFNFQ3hQMEZUNlI1NkQNCnFIV25kaFltWjlUQmFJOTJ6Mk0xdU1Icm5rSTRRQkU1M1VXb1JJSXBXSGRHbXNlOXNIU0tFaitRNHh4dnBXbWUNCjFDQm1abUl5YVBkMlZ2S1pRK01ta1pSNlgrMTQ3eGZQUkFPV2YzNmMra1pIR2MxbEREbkw3YTF5U01QQzQrNTUNCm13NmZ6TWlXNGwxeENSa1FFU09Ha1paTXJXUmMrdUpBb2Y4b090dHBRNHRiZ2N1bGhIRlpIKzF6Wjg0T3NjeUENCkVUVlpSMGZ6RVVIL1NYZm0zcEVoWGZ6alpTbWgrUFQ4UHNDeWE0SUZSR3pVN0VIYStKeTVYUVd3NU5pYnZSeG4NCjdPTHZKQkQvd1owMlh6aFI0UEhkZmZqWjZXenVCOXNRTVVjN3FFbXR4TGFuWjdPYjVIdHNWdWNwRWZTc0ZsQzcNClQrU09WNzExcGxnajZnS1RnaDVYYXBGL0VnbElIcDMvdnRCeWhmb1BEc3JoZ2U2UDlFSmZ4Y3Z2bXdVRVRsWmsNClM2WUZ3NzRaWk5Xc3RSMEg2NTZvZDZmVXN2M1AKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
