apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-operator
rules:
  - apiGroups:
      - zalando.org
    resources:
      - fabricgateways
      - fabricgateways/status
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-operator
subjects:
  - kind: ServiceAccount
    name: fabric
    namespace: fabric
roleRef:
  kind: ClusterRole
  name: gateway-operator
  apiGroup: rbac.authorization.k8s.io
