apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: "{{{ COMPOSITE_CONTROLLER_NAME }}}-new"
spec:
  generateSelector: true
  resyncPeriodSeconds: 5
  parentResource:
    apiVersion: zalando.org/v1
    resource: "{{{ CRD_PLURAL }}}"
  childResources:
    - apiVersion: networking.k8s.io/v1beta1
      resource: ingresses
      updateStrategy:
        method: InPlace
  hooks:
    sync:
      webhook:
        url: "http://{{{ COMPOSITE_CONTROLLER_NAME }}}/new-synch"