apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fabric-gateway-k8s-api-access
rules:
  - apiGroups:
      - zalando.org
    resources:
      - stacksets
    verbs:
      - get